[build]
  functions = "netlify/functions/"

[[redirects]]
  from = "/api/lists/*"
  to = "/.netlify/functions/lists"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200