[build]
  functions = "api/"

# Include all files in all functions
[functions]
  directory = "api/"
  node_bundler = "esbuild"
  included_files = ["assets/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200