[build]
  functions = "netlify/functions/"

# Include all files in all functions
[functions]
  node_bundler = "esbuild"
  included_files = ["assets/**", "views/**"]

[[redirects]]
  from = "/api/lists/*"
  to = "/.netlify/functions/lists"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200