[build]
  functions = "netlify/functions/"

# Include all files in all functions
[functions]
  directory = "netlify/functions/"
  node_bundler = "esbuild"
  included_files = ["assets/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200